version: '3.8'

# x-common-variables: &common-variables
#   MYSQL_DATABASE: books
#   MYSQL_USER: MYSQL_USER
#   MYSQL_PASSWORD: MYSQL_PASSWORD

services:
  mongo_db:
    image: mongo
    restart: always
    # volumes:
    #   - data:/data/db
    # ports:
    #   - "27017:27017"
    container_name: shop_db

  nginx:
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:8080"

  backend:
    build:
      dockerfile: Dockerfile
      context: "./"
    depends_on:
      - mongo_db
    # volumes:
    #   - /app/node_modules
    #   - ./server:/app
    ports:
      - "80:80"

  frontend:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./frontend/
    # volumes:
    #   - /app/node_modules
    #   - ./client:/app
    ports:
      - "4000:4000"
    depends_on:
      - backend

  # adminer:
  #     image: adminer:latest
  #     restart: unless-stopped
  #     ports:
  #       - 8000:8080
  #     depends_on:
  #       - mongo_db
  #     environment:
  #       ADMINER_DEFAULT_SERVER: mongo_db