version: '3.8'

# x-common-variables: &common-variables
#   MYSQL_DATABASE: books
#   MYSQL_USER: MYSQL_USER
#   MYSQL_PASSWORD: MYSQL_PASSWORD

services:
  mongo_db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    container_name: shop_db
    networks:
      - proshop-network
    

  # nginx:
  #   depends_on:
  #     - backend
  #     - frontend
  #   restart: always
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./nginx
  #   ports:
  #     - "5050:8000"

  backend:
    build:
      dockerfile: Dockerfile
      context: "./"
    depends_on:
      - mongo_db
    # volumes:
    #   - /app/node_modules
    #   - ./server:/app
    ports:
      - 5001:5001
    networks:
      - proshop-network
    environment:
      - MONGO_URI=mongodb://27017:27017

  frontend:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - backend=http://backend:5001
    build:
      dockerfile: Dockerfile
      context: ./frontend/
    # volumes:
    #   - /app/node_modules
    #   - ./client:/app
    ports:
      - 3000:3000
    # expose:
    #   - 4001
    depends_on:
      - backend
      
    networks:
      - proshop-network

networks:
    proshop-network:
        driver: bridge
volumes:
    mongo-data:
        driver: local