version: '3.8'

services:
  # mongo_db:
  #   image: mongo
  #   restart: always
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - mongo-data:/data/db
  #   container_name: shop_db
  #   networks:
  #     - proshop-network

  backend:
    image: laimax/proshop:backend
    # depends_on:
      # - mongo_db
    ports:
      - 5001:5001
    networks:
      - proshop-network
    # environment:
      # - MONGO_URI=mongodb://27017:27017

  frontend:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - backend=http://backend:5001
    image: laimax/proshop:frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
      
    networks:
      - proshop-network

networks:
    proshop-network:
        driver: bridge
volumes:
    mongo-data:
        driver: local